[build]
  publish = "dist/"
  command  = "npm run build"
  functions = "functions"

[dev]
  targetPort = 8080
  publish = "/dist"
  command = "npm run dev"

[[redirects]]
    from="/*"
    to="/.netlify/functions/server/:splat"
    status=200