[build]
  base = "/"
  publish = "dist/"
  command  = "npm run build"
  functions = "./functions"

[context.production]
  environment = { NODE_VERSION = "16.14.1" }

[[redirects]]
    to="/.netlify/functions/server/:splat"
    from="/*"
    status=200